remote_theme: wu-lee/jekyll-theme-monos
title: Rushkoff Archive
description: Douglas Rushkoff's Article Archive
unpublished: false
collections:
  articles:
    output: true
  publications:
    output: true
defaults:
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'publications'
    values:
      layout: 'publication'
plugins:
  - jekyll-remote-theme
