theme: jekyll-theme-slate
title: Rushkoff Archive
description: Douglas Rushkoff's Article Archive
unpublished: false
collections:
  articles:
    output: true
defaults:
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  
