remote_theme: wu-lee/jekyll-theme-monos
title: Rushkoff Archive
description: Douglas Rushkoff's Article Archive
unpublished: false
collections:
  # Define our collections and their properties
  articles:
    item_desc: Article
    icon_class: fa fa-newspaper-o
    output: true
  publications:
    item_desc: Publication
    icon_class: fa fa-university
    output: true
  categories:
    item_desc: Category
    icon_class: fa fa-tag
    output: true
  videos_elsewhere:
    item_desc: Video
    icon_class: fa fa-film
    output: true
  misc_elsewhere:
    item_desc: Misc
    icon_class: fa fa-asterisk
    output: true
defaults:
  # Set the default front-matter fields for various content types
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'publications'
    values:
      layout: 'publication'
  - scope:
      path: ''
      type: 'categories'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'videos_elsewhere'
    values:
      layout: 'video_elsewhere'
  - scope:
      path: ''
      type: 'misc_elsewhere'
    values:
      layout: 'article'
plugins:
  - jekyll-remote-theme
  - jekyll-feed
feed:
  collections:
    - articles
    - videos_elsewhere
