remote_theme: wu-lee/jekyll-theme-monos
title: Rushkoff Archive
description: Douglas Rushkoff's Article Archive
unpublished: false
collections:
  # Define our collections and their properties
  articles:
    output: true
  publications:
    output: true
  categories:
    output: true
  videos_elsewhere:
    output: true
defaults:
  # Set the default front-matter fields for various content types
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'publications'
    values:
      layout: 'publication'
  - scope:
      path: ''
      type: 'categories'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'videos_elsewhere'
    values:
      layout: 'video_elsewhere'
plugins:
  - jekyll-remote-theme
  - jekyll-feed
feed:
  collections:
    - articles
    - videos_elsewhere
